// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportEngine.Domain.Database.Context;

#nullable disable

namespace ReportEngine.Domain.Migrations
{
    [DbContext(typeof(ReAppContext))]
    [Migration("20251021035054_NullablePurposes")]
    partial class NullablePurposes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportEngine.Domain.Entities.AdditionalEquipPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("CostPerUnit")
                        .HasColumnType("real");

                    b.Property<int>("FormedAdditionalEquipId")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Measure")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FormedAdditionalEquipId");

                    b.ToTable("AdditionalEquipPurposes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Armautre.CarbonArmature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CarbonArmatures");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Armautre.HeaterArmature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HeaterArmatures");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Armautre.StainlessArmature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("StainlessArmatures");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Braces.BoxesBrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BoxesBraces");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Braces.DrainageBrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrainageBraces");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Braces.SensorBrace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SensorsBraces");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RegisterDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ContainersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProjectInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("StandsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectInfoId");

                    b.ToTable("ContainersBatch");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerStand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContainerBatchId")
                        .HasColumnType("integer");

                    b.Property<float?>("ContainerWeight")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProjectInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("StandsCount")
                        .HasColumnType("integer");

                    b.Property<float>("StandsWeight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContainerBatchId");

                    b.HasIndex("ProjectInfoId");

                    b.ToTable("ContainersStand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Drainage.Drainage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Drainages");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.DrainagePurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("CostPerUnit")
                        .HasColumnType("real");

                    b.Property<int>("FormedDrainageId")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Measure")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FormedDrainageId");

                    b.ToTable("DrainagePurposes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricComponents.CabelBoxe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabel")
                        .HasColumnType("integer");

                    b.Property<int>("CabelInput")
                        .HasColumnType("integer");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ElectricProtection")
                        .HasColumnType("integer");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabelBoxes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricComponents.CabelInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabel")
                        .HasColumnType("integer");

                    b.Property<int>("CabelInput")
                        .HasColumnType("integer");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ElectricProtection")
                        .HasColumnType("integer");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabelInputs");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricComponents.CabelProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabel")
                        .HasColumnType("integer");

                    b.Property<int>("CabelInput")
                        .HasColumnType("integer");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ElectricProtection")
                        .HasColumnType("integer");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabelProductions");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricComponents.CabelProtection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabel")
                        .HasColumnType("integer");

                    b.Property<int>("CabelInput")
                        .HasColumnType("integer");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ElectricProtection")
                        .HasColumnType("integer");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabelProtections");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricComponents.Heater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cabel")
                        .HasColumnType("integer");

                    b.Property<int>("CabelInput")
                        .HasColumnType("integer");

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ElectricProtection")
                        .HasColumnType("integer");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Heaters");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricSockets.CarbonSocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CarbonSockets");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricSockets.HeaterSocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HeaterSockets");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricSockets.StainlessSocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("StainlessSockets");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricalPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("CostPerUnit")
                        .HasColumnType("real");

                    b.Property<int>("FormedElectricalComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Measure")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FormedElectricalComponentId");

                    b.ToTable("ElectricalPurposes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedAdditionalEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormedAdditionalEquips");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedDrainage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormedDrainages");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedElectricalComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FormedElectricalComponents");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<string>("Designe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("FormedFrames");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Frame.FrameDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FrameDetails");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Frame.FrameRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FrameRolls");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Frame.PillarEqiup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PillarEqiups");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FrameComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("ComponentName")
                        .HasColumnType("text");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("CostComponent")
                        .HasColumnType("real");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("FormedFrameId")
                        .HasColumnType("integer");

                    b.Property<float?>("Length")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormedFrameId");

                    b.ToTable("FrameComponents");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Obvyazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Clamp")
                        .HasColumnType("real");

                    b.Property<float>("HumanCost")
                        .HasColumnType("real");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("LineLength")
                        .HasColumnType("real");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("OtherLineCount")
                        .HasColumnType("integer");

                    b.Property<int>("Sensor")
                        .HasColumnType("integer");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TreeSocket")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("WidthOnFrame")
                        .HasColumnType("real");

                    b.Property<float>("ZraCount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Obvyazki");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ObvyazkaInStand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Armature")
                        .HasColumnType("text");

                    b.Property<string>("ArmatureCostPerUnit")
                        .HasColumnType("text");

                    b.Property<float?>("ArmatureCount")
                        .HasColumnType("real");

                    b.Property<string>("ArmatureMeasure")
                        .HasColumnType("text");

                    b.Property<float?>("Clamp")
                        .HasColumnType("real");

                    b.Property<string>("FirstSensorDescription")
                        .HasColumnType("text");

                    b.Property<string>("FirstSensorKKS")
                        .HasColumnType("text");

                    b.Property<string>("FirstSensorMarkMinus")
                        .HasColumnType("text");

                    b.Property<string>("FirstSensorMarkPlus")
                        .HasColumnType("text");

                    b.Property<string>("FirstSensorType")
                        .HasColumnType("text");

                    b.Property<float?>("HumanCost")
                        .HasColumnType("real");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<string>("KMCH")
                        .HasColumnType("text");

                    b.Property<string>("KMCHCostPerUnit")
                        .HasColumnType("text");

                    b.Property<float?>("KMCHCount")
                        .HasColumnType("real");

                    b.Property<string>("KMCHMeasure")
                        .HasColumnType("text");

                    b.Property<float?>("LineLength")
                        .HasColumnType("real");

                    b.Property<string>("MaterialLine")
                        .HasColumnType("text");

                    b.Property<string>("MaterialLineCostPerUnit")
                        .HasColumnType("text");

                    b.Property<float?>("MaterialLineCount")
                        .HasColumnType("real");

                    b.Property<string>("MaterialLineMeasure")
                        .HasColumnType("text");

                    b.Property<int?>("NN")
                        .HasColumnType("integer");

                    b.Property<int>("ObvyazkaId")
                        .HasColumnType("integer");

                    b.Property<string>("ObvyazkaName")
                        .HasColumnType("text");

                    b.Property<int?>("OtherLineCount")
                        .HasColumnType("integer");

                    b.Property<string>("SecondSensorDescription")
                        .HasColumnType("text");

                    b.Property<string>("SecondSensorKKS")
                        .HasColumnType("text");

                    b.Property<string>("SecondSensorMarkMinus")
                        .HasColumnType("text");

                    b.Property<string>("SecondSensorMarkPlus")
                        .HasColumnType("text");

                    b.Property<string>("SecondSensorType")
                        .HasColumnType("text");

                    b.Property<int?>("Sensor")
                        .HasColumnType("integer");

                    b.Property<string>("SensorType")
                        .HasColumnType("text");

                    b.Property<int>("StandId")
                        .HasColumnType("integer");

                    b.Property<string>("ThirdSensorDescription")
                        .HasColumnType("text");

                    b.Property<string>("ThirdSensorKKS")
                        .HasColumnType("text");

                    b.Property<string>("ThirdSensorMarkMinus")
                        .HasColumnType("text");

                    b.Property<string>("ThirdSensorMarkPlus")
                        .HasColumnType("text");

                    b.Property<string>("ThirdSensorType")
                        .HasColumnType("text");

                    b.Property<string>("TreeSocket")
                        .HasColumnType("text");

                    b.Property<float?>("TreeSocketCount")
                        .HasColumnType("real");

                    b.Property<string>("TreeSocketMaterialCostPerUnit")
                        .HasColumnType("text");

                    b.Property<float?>("TreeSocketMaterialCount")
                        .HasColumnType("real");

                    b.Property<string>("TreeSocketMaterialMeasure")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.Property<float?>("WidthOnFrame")
                        .HasColumnType("real");

                    b.Property<float?>("ZraCount")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ObvyazkaId");

                    b.HasIndex("StandId");

                    b.ToTable("ObvyazkiInStands");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Other.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Other.Other", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Others");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Pipes.CarbonPipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CarbonPipes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Pipes.HeaterPipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HeaterPipes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Pipes.StainlessPipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cost")
                        .HasColumnType("real");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<int>("ExportDays")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("StainlessPipes");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ProjectInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<float>("HumanCost")
                        .HasColumnType("real");

                    b.Property<bool>("IsGalvanized")
                        .HasColumnType("boolean");

                    b.Property<string>("Manager")
                        .HasColumnType("text");

                    b.Property<string>("MarkMinus")
                        .HasColumnType("text");

                    b.Property<string>("MarkPlus")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Object")
                        .HasColumnType("text");

                    b.Property<string>("OrderCustomer")
                        .HasColumnType("text");

                    b.Property<DateOnly>("OutOfProduction")
                        .HasColumnType("date");

                    b.Property<string>("RequestProduction")
                        .HasColumnType("text");

                    b.Property<int>("StandCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Stand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Armature")
                        .HasColumnType("text");

                    b.Property<string>("BraceType")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("ContainerStandId")
                        .HasColumnType("integer");

                    b.Property<string>("Design")
                        .HasColumnType("text");

                    b.Property<string>("DesigneStand")
                        .HasColumnType("text");

                    b.Property<int>("Devices")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageType")
                        .HasColumnType("text");

                    b.Property<string>("KKSCode")
                        .HasColumnType("text");

                    b.Property<string>("KMCH")
                        .HasColumnType("text");

                    b.Property<string>("MaterialLine")
                        .HasColumnType("text");

                    b.Property<int>("NN")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("ObvyazkaType")
                        .HasColumnType("text");

                    b.Property<int>("ProjectInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("StandSummCost")
                        .HasColumnType("numeric");

                    b.Property<string>("TreeSocket")
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ContainerStandId");

                    b.HasIndex("ProjectInfoId");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandAdditionalEquip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditionalEquipId")
                        .HasColumnType("integer");

                    b.Property<int>("StandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalEquipId");

                    b.HasIndex("StandId");

                    b.ToTable("StandAdditionalEquips");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandDrainage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DrainageId")
                        .HasColumnType("integer");

                    b.Property<int>("StandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrainageId");

                    b.HasIndex("StandId");

                    b.ToTable("StandDrainages");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandElectricalComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectricalComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("StandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElectricalComponentId");

                    b.HasIndex("StandId");

                    b.ToTable("StandElectricalComponents");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FrameId")
                        .HasColumnType("integer");

                    b.Property<int>("StandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.HasIndex("StandId");

                    b.ToTable("StandFrames");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cabinet")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneContact")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<int?>("SystemRole")
                        .HasColumnType("integer");

                    b.Property<string>("UserLogin")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.AdditionalEquipPurpose", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedAdditionalEquip", "FormedAdditionalEquip")
                        .WithMany("Purposes")
                        .HasForeignKey("FormedAdditionalEquipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormedAdditionalEquip");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerBatch", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.ProjectInfo", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerStand", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.ContainerBatch", "Batch")
                        .WithMany("Containers")
                        .HasForeignKey("ContainerBatchId");

                    b.HasOne("ReportEngine.Domain.Entities.ProjectInfo", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.DrainagePurpose", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedDrainage", "FormedDrainage")
                        .WithMany("Purposes")
                        .HasForeignKey("FormedDrainageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormedDrainage");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ElectricalPurpose", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedElectricalComponent", "FormedElectricalComponent")
                        .WithMany("Purposes")
                        .HasForeignKey("FormedElectricalComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormedElectricalComponent");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FrameComponent", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedFrame", "FormedFrame")
                        .WithMany("Components")
                        .HasForeignKey("FormedFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormedFrame");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ObvyazkaInStand", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.Obvyazka", "Obvyazka")
                        .WithMany()
                        .HasForeignKey("ObvyazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportEngine.Domain.Entities.Stand", "Stand")
                        .WithMany("ObvyazkiInStand")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obvyazka");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Stand", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.ContainerStand", null)
                        .WithMany("Stands")
                        .HasForeignKey("ContainerStandId");

                    b.HasOne("ReportEngine.Domain.Entities.ProjectInfo", "Project")
                        .WithMany("Stands")
                        .HasForeignKey("ProjectInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandAdditionalEquip", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedAdditionalEquip", "AdditionalEquip")
                        .WithMany("StandAdditionalEquips")
                        .HasForeignKey("AdditionalEquipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportEngine.Domain.Entities.Stand", "Stand")
                        .WithMany("StandAdditionalEquips")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalEquip");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandDrainage", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedDrainage", "Drainage")
                        .WithMany("StandDrainages")
                        .HasForeignKey("DrainageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportEngine.Domain.Entities.Stand", "Stand")
                        .WithMany("StandDrainages")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drainage");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandElectricalComponent", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedElectricalComponent", "ElectricalComponent")
                        .WithMany("StandElectricalComponents")
                        .HasForeignKey("ElectricalComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportEngine.Domain.Entities.Stand", "Stand")
                        .WithMany("StandElectricalComponent")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectricalComponent");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.StandFrame", b =>
                {
                    b.HasOne("ReportEngine.Domain.Entities.FormedFrame", "Frame")
                        .WithMany("StandFrames")
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportEngine.Domain.Entities.Stand", "Stand")
                        .WithMany("StandFrames")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerBatch", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ContainerStand", b =>
                {
                    b.Navigation("Stands");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedAdditionalEquip", b =>
                {
                    b.Navigation("Purposes");

                    b.Navigation("StandAdditionalEquips");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedDrainage", b =>
                {
                    b.Navigation("Purposes");

                    b.Navigation("StandDrainages");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedElectricalComponent", b =>
                {
                    b.Navigation("Purposes");

                    b.Navigation("StandElectricalComponents");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.FormedFrame", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("StandFrames");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.ProjectInfo", b =>
                {
                    b.Navigation("Stands");
                });

            modelBuilder.Entity("ReportEngine.Domain.Entities.Stand", b =>
                {
                    b.Navigation("ObvyazkiInStand");

                    b.Navigation("StandAdditionalEquips");

                    b.Navigation("StandDrainages");

                    b.Navigation("StandElectricalComponent");

                    b.Navigation("StandFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
